from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib import colors

from datetime import datetime


def generate_pdf_report(
    filename,
    vehicle_type,
    health_score,
    severity,
    predicted_rul,
    adjusted_km,
    risk_score,
    risk_level,
    recommendations
):

    doc = SimpleDocTemplate(
        filename
    )

    styles = getSampleStyleSheet()

    content = []

    title = Paragraph(
        "AI Tyre Health Inspection Report",
        styles["Title"]
    )

    content.append(title)

    content.append(
        Spacer(1, 20)
    )

    inspection_date = (
        datetime.now()
        .strftime("%d-%m-%Y %H:%M")
    )

    details = f"""
    <b>Inspection Date:</b> {inspection_date}<br/>
    <b>Vehicle Type:</b> {vehicle_type}<br/>
    <b>Health Score:</b> {health_score:.0f}/100<br/>
    <b>Severity:</b> {severity}<br/>
    <b>Predicted RUL:</b> {predicted_rul:,.0f} km<br/>
    <b>Adjusted KM Left:</b> {adjusted_km:,.0f} km<br/>
    <b>Risk Score:</b> {risk_score:.0f}/100<br/>
    <b>Risk Level:</b> {risk_level}
    """

    content.append(
        Paragraph(
            details,
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Recommendations",
            styles["Heading2"]
        )
    )

    for i, rec in enumerate(
        recommendations,
        start=1
    ):

        content.append(
            Paragraph(
                f"{i}. {rec}",
                styles["BodyText"]
            )
        )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Generated by AI Tyre Health Inspection System",
            styles["Italic"]
        )
    )

    doc.build(content)

    return filename